#!/usr/bin/env python3
"""Auto-derive a course-specific chapter dictionary from the upstream cwa
GitHub repo's branch list. Falls back to a hand-written stub if the repo has
no usable branches.

Usage:
    derive_chapter_dict.py <course-slug> <upstream-repo-path> > chapter-dict.yaml

The output is consumed by infer_chapter_assignment.py via the --dict flag.
Each chapter entry has:
  - id (chXX)
  - title (cleaned-up branch suffix)
  - keywords by weight (3=strong, 2=moderate, 1=weak) derived from the branch
    name's tokens + manual augments
"""
from __future__ import annotations
import argparse, re, subprocess, sys
from pathlib import Path


def list_branches(repo_path: Path) -> list[str]:
    """Get all remote branches matching a chapter-numbering pattern."""
    res = subprocess.run(
        ["git", "-C", str(repo_path), "branch", "-a"],
        capture_output=True, text=True, check=True,
    )
    branches = []
    for line in res.stdout.splitlines():
        line = line.strip().lstrip("*").strip()
        # Match patterns like "remotes/origin/01-project-setup" or "01-foo"
        m = re.match(r"(?:remotes/origin/)?(\d{2}[-_].+)$", line)
        if m:
            branches.append(m.group(1))
    return sorted(set(branches))


def chapter_tokens(branch: str) -> tuple[str, str, list[str]]:
    """Split '01-project-setup-component-architecture' → ('ch01', 'Project setup component architecture', ['project', 'setup', 'component', 'architecture'])"""
    m = re.match(r"^(\d{2})[-_](.+)$", branch)
    if not m:
        return ("ch??", branch, [])
    num = m.group(1)
    suffix = m.group(2).replace("_", "-")
    title = suffix.replace("-", " ").strip().capitalize()
    tokens = [t for t in re.split(r"[-_]+", suffix) if t and len(t) > 2]
    return (f"ch{num}", title, tokens)


def expand_keywords(tokens: list[str]) -> dict[int, list[str]]:
    """Expand chapter-name tokens into a weighted keyword dict.
    Heuristic: each token gets weight 3 (strong); we also add common bigrams
    formed by adjacent tokens at weight 2; single domain words at weight 1."""
    if not tokens:
        return {3: [], 2: [], 1: []}
    strong = list(tokens)
    moderate = []
    for i in range(len(tokens) - 1):
        moderate.append(f"{tokens[i]} {tokens[i+1]}")
    # Also include the full chapter title as one moderate keyword
    moderate.append(" ".join(tokens))
    weak = []  # left empty; operator can add later
    return {3: strong, 2: moderate, 1: weak}


def fallback_dict(course: str) -> list[dict]:
    """When no usable branches exist, emit a 6-chapter stub that the operator
    can edit. Six is the median chapter count across nightcode-style courses."""
    return [
        {"id": f"ch{i:02d}", "title": f"Chapter {i}", "branch": None,
         "keywords": {3: [], 2: [], 1: []}}
        for i in range(1, 7)
    ]


def emit_yaml(course: str, chapters: list[dict]) -> str:
    out = [f"# Auto-derived chapter dictionary for {course}"]
    out.append("# Generated by derive_chapter_dict.py from upstream cwa branch list.")
    out.append("# Edit keywords below to improve assignment accuracy after first run.")
    out.append("")
    out.append(f"course: {course}")
    out.append("chapters:")
    for ch in chapters:
        out.append(f"  - id: {ch['id']}")
        out.append(f"    title: {ch['title']!r}")
        if ch.get("branch"):
            out.append(f"    branch: {ch['branch']}")
        out.append("    keywords:")
        for w in (3, 2, 1):
            kws = ch["keywords"].get(w, [])
            if kws:
                out.append(f"      {w}: {kws}")
            else:
                out.append(f"      {w}: []")
    return "\n".join(out) + "\n"


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("course", help="course slug (e.g. trello-clone)")
    p.add_argument("upstream", type=Path, help="path to upstream cwa repo")
    p.add_argument("-o", "--output", type=Path, help="output yaml path (default stdout)")
    args = p.parse_args(argv)

    if not args.upstream.is_dir():
        print(f"upstream path not found: {args.upstream}", file=sys.stderr)
        return 1

    try:
        branches = list_branches(args.upstream)
    except subprocess.CalledProcessError as e:
        print(f"git failed: {e}", file=sys.stderr)
        return 2

    if not branches:
        print(f"  no chapter-numbered branches found at {args.upstream} — emitting 6-chapter stub", file=sys.stderr)
        chapters = fallback_dict(args.course)
    else:
        chapters = []
        for b in branches:
            ch_id, title, tokens = chapter_tokens(b)
            chapters.append({
                "id": ch_id,
                "title": title,
                "branch": b,
                "keywords": expand_keywords(tokens),
            })

    yaml_text = emit_yaml(args.course, chapters)
    if args.output:
        args.output.write_text(yaml_text)
        print(f"  ✓ {len(chapters)} chapters → {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(yaml_text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
